# ***WARNING: SERVER WILL NOT RECOGNIZE NEW EDITS UNTIL RESTARTED***
# ***WARNING: YOU MUST DELETE OR CHANGE THE NAME OF OLD CONFIG FOR AN UPDATED ONE TO BE GENERATED***
#
#   ## PERMISSIONS ##
# All triggers come with a default permission of "commandtriggers.triggername", regardless of other assigned permissions.
# The trigger will only initiate if the triggering player has ANY of the designated permissions.
# All newly defined permissions will register DEFAULT TO FALSE. You must assign them using a permission plugin.
#
#   ## EVENTS ##
# The possible events include:
#   - onPlayerRespawn
#   - onPlayerItemConsume   (material event)
#   - onPlayerJoin
#   - onPlayerItemBreak     (material event)
#   - onPlayerChangedWorld
#   - onPlayerDeath
#   - onPlayerItemHeld      (material event)
#   - onPlayerItemUse       (material event)  ##this is not a native spigot event, but it's executed when a player right clicks with an item
#   - onBlockPlace          (material event)
#   - onBlockBreak          (material event)
# *REFER TO SPIGOT DOCUMENTATION FOR EVENT EXPLANATION
# *Be sure to use empty curly brackets after events without arguments "onPlayerJoin: {}" or they won't be recognized.
#
#   ## COMMANDS ##
# playerCommands will be executed automatically by the player. (make sure to use a "/" before these)
# serverCommands will be executed automatically by the server.
# Instances of {player} in the commands will be replaced with the activating-player's name.
# BE SURE TO ESCAPE ANY YML RECOGNIZED CHARACTERS IN A COMMAND TEXT.
# Example of escaping recognized characters with a backslash: "\\", "\"test\""
#
#   ## MATERIAL ARGUMENTS ##
# The materials event argument is a whitelist of items accepted for triggering the event.
# The notMaterials event argument is a blacklist of items not accepted for triggering the event.
# It would not make logical sense to attempt to use both at the same time.
# Using * before the material string will add any materials that contain the given text.
# Quotations may not be necessary around material definitions, but keep yml from parsing the text.


triggers:
# this trigger will initiate when a player with permission consumes a golden apple or joins the server
  exampletrigger:
    events:
      onPlayerJoin: {}
      onPlayerItemConsume:
        materials:
          - "GOLDEN_APPLE"
    serverCommands:
      - "give {player} minecraft:golden_apple 1"
    playerCommands:
      - "/give {player} minecraft:golden_apple 1"
    permissions:
      - examplepermission.exampletrigger

# this trigger will initiate when a player with permission consumes anything other than a golden apple or respawns or rightclicks with any pickaxe
  exampletrigger2:
    events:
      onPlayerRespawn: {}
      onPlayerItemUse:
        materials:
          - "*_PICKAXE"
      onPlayerItemConsume:
        notMaterials:
          - "GOLDEN_APPLE"
    serverCommands:
      - "give {player} minecraft:apple 1"
    permissions:
      - examplepermission.exampletrigger
